### ISSUE TITLE
[REQUEST] Have a way to stage Best Practices content on staging.gtfs.org

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs.org#28]
## Current situation
Same content [script](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh) is run on master and production branch via `npm run fetchdata`

### GTFS static
- [clone google/transit](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L14)
- [extract reference.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L17) (en)
- [extract CHANGES.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L26) (en)

### GTFS Realtime v2
- [extract reference.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L32)
- [extract CHANGES.MD](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L35) (en)
- [extract reference.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L41) (es)

### GTFS Realtime v1
- [navigate local git copy of google/transit and checkout tags/v1.0](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L45)
- [extract reference.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L48) (en)
- [extract reference.md](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L53) (es)

### GTFS Best Practices
- [clone `docsv2` branch of MobilityData/gtfs-best-practices](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L57)
- extract all files from [predefined list](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L58) (en)
- [extract all files](https://github.com/MobilityData/gtfs.org/blob/a4f9c745b4c4446166d1c4d6e3cc84c27799b3f4/scripts/fetchdata.sh#L83) from predefined list (es)

## GTFS Static and GTFS Realtime v1&2
_**untouched**_

## GTFS Best Practices

- **differentiate content fetch script** on master branch and production branch
- master branch will clone master of MobilityData/gtfs-best-practices --> deployed on staging.gtfs.org
- production branch will clone production of MobilityData/gtfs-best-practices --> deployed on GTFS.org

# TODO to get there

- [x] simplify fetch script in regards to language (see next step for details) for gtfs-best-practices
- [x] merge `docsv2`on `master` of mobilitydata/gtfs-best-practices. Requires content fetching script simplification to account for that [commit](https://github.com/MobilityData/gtfs-best-practices/commit/16cbc45a2864b6361c3a694bc2accca3f4919912) @antrim 
- [x] create new branch `production` from `master` in mobilitydata/gtfs-best-practices
- [x] point script of `master` branch of mobilitydata/gtfs.org to `production` branch of mobilitydata/gtfs-best-practices
- [x] merge `master`branch of MobilityData/gtfs.org to `production`
- [x] point script of `master` branch of mobilitydata/gtfs.org to `master` branch of mobilitydata/gtfs-best-practices

**Comment by fabrice-v** [comment]
**simplify fetch script in regards to language (see next step for details) for gtfs-best-practices**

https://github.com/MobilityData/gtfs.org/pull/29

**Comment by fabrice-v** [comment]
**merge docsv2on master of mobilitydata/gtfs-best-practices.**
https://github.com/MobilityData/gtfs-best-practices/commit/9346e05a7ad59dafe319aec70a47da8209f284e9

**Comment by fabrice-v** [comment]
**create new branch production from master in mobilitydata/gtfs-best-practices**

https://github.com/MobilityData/gtfs-best-practices/tree/production

**Comment by fabrice-v** [comment]
**point script of master branch of mobilitydata/gtfs.org to production branch of mobilitydata/gtfs-best-practices**

https://github.com/MobilityData/gtfs.org/commit/5681d64c636bd16cd61346d4ffd5b4d4ebecd5d8

**Comment by fabrice-v** [comment]
**merge masterbranch of MobilityData/gtfs.org to production**

https://github.com/MobilityData/gtfs.org/pull/30

**Comment by fabrice-v** [comment]
**point script of master branch of mobilitydata/gtfs.org to master branch of mobilitydata/gtfs-best-practices**

https://github.com/MobilityData/gtfs.org/commit/4e90683636bc5b90b47832019d5a695f9c8abca5

**Comment by fabrice-v** [comment]
Done. New content can now be merged into `master` branch of https://github.com/MobilityData/gtfs-best-practices and will appear on staging.gtfs.org

**Comment by fabrice-v** [comment]
Validated via
https://github.com/MobilityData/gtfs-best-practices/commit/bde090a6bd50553b0f5aa28e33de6e65b52751d8
Result:
![image](https://user-images.githubusercontent.com/55884852/71205563-a6e61700-2270-11ea-8280-7e243df6b3d0.png)
