### ISSUE TITLE
[translations] Translate new site

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#493]
This is an epic issue intended to plan for translating the site. 

## Context
gtfs.org has translations in the following languages:
1. German (`de`)
2. Spanish (`es`)
3. French (`fr`)
4. Indonesian (`id`)
5. Japanese (`jp`)
6. Portugese (`pt`) (Portugese Brazilian (`pt_BR`) is not supported)
7. Russian (`ru`)
8. Corean (`ko`)
9. Chinese traditional (`zh_TW`)
10. Chinese simplified (`zh`)

Given that our previous translation system was very time intensive, @fredericsimard has worked on a [new tool](https://github.com/MobilityData/mbd-translation-tool) to manage translations. 

As part of the new gtfs.org release, we've decided that it would be quicker to re-translate the whole site from scratch instead of trying to reuse what we already have.

## Scope for translations
- the translations in all the languages above are up to date
- we have a process in place so that translations are updated in every PR on gtfs.org (i. e. no translation backlog accumulation)

## To do
**1. Review and update the glossaries.**
- [x] add all words in `code formatting` in the [glossaries](https://github.com/MobilityData/mbd-translation-tool/tree/main/glossaries-for-google-translate-api)
- [ ] Add requirement language words for languages other than French and Spanish
- [ ] Add GTFS features for every language (#492)

**2. Translate the site in every language described above.**
Note that **ideally**, the output of the translations is final and if we need to make changes, it should be done via the glossaries. 
That being said, we received good feedback feedback on the Japanese translations from Google, and it would be nice to try and integrate them. They are [in this document](https://docs.google.com/document/d/1w3Ysgas6YPXWp5CuliI05SrZFRoLhYOOOaGcPk_ODpE/edit?resourcekey=0-I8HbZjd1Fk0-2ybKkOXwrw). 

**3. Set-up the process to maintain the translations moving forward.**
We want to avoid having a translation backlog, so we'd like translations to be done in every PR, as a requirement before merging.

**Comment by fredericsimard** [comment]
To add to the "3. Set-up the process to maintain the translations moving forward." step, I have found out it is possible to automate the translation of files when a PR is created, the files will be added to the same PR automatically. Someone will then have the opportunity to revise them for contents, and grammar/spelling if they are able/wishing to.

I have an action ready to test when Elrond is officially published.
